name: Build StreamRoulette WPF

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    permissions:
      contents: write

    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # Перевірте версію (було 10.0.x, але актуальна 8 або 9)

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Publish
      run: |
        dotnet publish -c ${{ matrix.configuration }} -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish_output

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: StreamRoulette-App
        path: ./publish_output/StreamRoulette.exe

    - name: Create/Update Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./publish_output/StreamRoulette.exe
        tag_name: latest
        name: Latest Build
        draft: false
        prerelease: false
